#1. 시퀀스 자료형

In [2]:
#1.1 인덱싱
      #(-) 54321
          #01234
example = 'abcde'
print(example[0]) # 출력: a
print(example[2]) # 출력: c
print(example[-1]) # 출력: e

a
c
e


In [4]:
#1.2 슬라이싱
          #54321
          #01234
example = 'abcde'
print(example[-4:-1]) # 출력: bc

bcd


In [ ]:
range(10)[3] # 출력: 3
range(100)[::5] # 출력: range(0, 100, 5)

In [7]:
# 1.3 특정항목 포함 여부
example = 'abcde'
print('a' in example) # 이게 맞음!

True


In [8]:
print('z' not in example) # 출력: False

True


In [9]:
#1.4 연결 & 반복
example1 = 'abcde'
example2 = 'f'
print(example1 + example2) # 출력: abcdef
print(example2 * 3)        # 출력: fff

abcdef
fff


In [10]:
# 내장함수를 사용!
example = 'abcde'
print(len(example))  # 출력: 5
print(min(example))  # 출력: a
print(max(example))  # 출력: e

5
a
e


#2. 시퀀스 자료형의 패킹과 언패킹

In [13]:
#2.1 튜플 패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)  # 출력: (1, 2, 3, 4)
type(packed_tuple)

(1, 2, 3, 4)


tuple

In [14]:
tuple_example = 1
print(tuple_example)
type(tuple_example)

1


int

In [15]:
#2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)

(1, 2, 3, 4)


In [18]:
# 튜플 언패킹
a, b, c, d = packed_tuple
print(a)  # 출력: 1
print(b)  # 출력: 2
print(c)  # 출력: 3
print(d)  # 출력: 4

1
2
3
4


In [25]:
# 다양한 패킹/언패킹
# range는 0부터 n-1까지 숫자를 생성하는 함수
a,b,c = range(3) #0,1,2
print(range(3))
print(a,b,c)

range(0, 3)
0 1 2


In [27]:
a, b, c, d, e = 'hello'
print(a)
print(b)
print(c)
print(d)
print(e)

h
e
l
l
o


In [28]:
a, b = [10, 20]
print(a)
print(b)

10
20


In [29]:
total_sum = 0

for i in range(5): #0,1,2,3,4
    total_sum += i
    print(total_sum)
print(total_sum)

0
1
3
6
10
10


In [30]:
# 별표를 이용한 언패킹
first, *middle, last = [1,2,3,4,5]
print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


In [34]:
first, *middle = [1,2,3,4,5]
print(first)
print(middle)

5
[1, 2, 3, 4]


#2. 리스트

In [ ]:
#리스트의 필요성

x1 = 100
x2 = 200
x3 = 300

x = [100,200,300]

In [36]:
#리스트의 장점 : 여러가지 자료형을 넣을수 있다.
z = [1, 'apple', 2.5, ['a', 'b'], (1, 2), True]
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])
print(z[5])

1
apple
2.5
['a', 'b']
(1, 2)
True


In [37]:
z = [
		1,
		'apple',
		2.5,
		['a', 'b'],
		(1, 2)
]
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])

1
apple
2.5
['a', 'b']
(1, 2)


In [38]:
#2.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000
print(a)

[10000, 2, 3, 4, 5]


In [39]:
# 문자열은 변경할수 없다.
s = 'licat'
print(s[0])
s[0] = 'k'

l


TypeError: ignored

In [40]:
# 3. 리스트안에 리스트

b = [[10, 20, 30], [1, 2, 3]]
print(b[1][2]) # 출력: 3

3


In [46]:
print(b)
print(b[0])
print(b[1])
print(b[0][2])

[[10, 20, 30], [1, 2, 3]]
[10, 20, 30]
[1, 2, 3]
30


In [ ]:
나이 직업구분
10    1
20    2
30    3


In [47]:
# 리스트의 덧셈
a = [1, 2, 3, 4, 5] # +[6,7,8]
b = [6, 7, 8]

print(a + b) # 출력: [1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]


In [55]:
l = [1, 2, 3]
print(type(l))
print(l)
print(l * 3)
print(l + l)

<class 'list'>
[1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [56]:
from re import L
import numpy as np

l = [1, 2, 3]
l = np.array(l)
print(l)
print(type(l))
print(l * 3)
print(l + l)
# 너무 당연하게 요소를 붙이는 것이다라고 생각하지 않으셨으면 좋겠습니다.

[1 2 3]
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [59]:
lst = [1, 2, 3, 4, 5]
print(lst[5])

IndexError: ignored

In [60]:
# 슬라이싱 실습!

l = [1, 2, 3, 4, 5]

print(l[:])     # 출력: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [61]:
print(l[::-1])  # 출력: [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


In [62]:
print(l[::2])   # 출력: [1, 3, 5]

[1, 3, 5]


In [63]:
print(l[0:4][::-1]) # 출력: [4, 3, 2, 1]

[4, 3, 2, 1]


In [ ]:
# 데이터가 크다. 내가 원하는대로 데이터를 추출하고 싶다.!
# 1. 샘플링 -> 1억개 데이터 -> 천개! -> 리스트 슬라이싱! 메서드! -> 1억개 데이터!

In [64]:
l = [1, 2, 3, 4, 5]
print(l[10:20]) # 출력: []

[]
